defmodule PhpBeam.Builtin.OpensslFns do
  @moduledoc """
  ext/openssl over OTP :crypto / :public_key — the cryptographic core:
  symmetric ciphers (aes cbc/ctr/ofb/gcm families through
  crypto_one_time, PKCS7 padding by default, base64 output unless
  OPENSSL_RAW_DATA), digests, RSA sign/verify (PKCS1 v1.5 — the common
  OPENSSL_ALGO_* set), RSA public/private encrypt+decrypt pairs, and the
  OpenSSLAsymmetricKey / OpenSSLCertificate objects carrying decoded keys
  in dt_state. CSR/CMS/PKCS7/PKCS12 families are stubbed (deferred.md).

  php's aes-128-cbc raw output byte-verified against the local php 8.4
  (same OpenSSL padding); signatures verified against a fixed 512-bit
  fixture generated by php itself.
  """

  alias PhpBeam.Classes.Table
  alias PhpBeam.Eval
  alias PhpBeam.PArray

  def register(fns) do
    entries = %{
      "openssl_digest" => &digest/2,
      "openssl_encrypt" => &sym_encrypt/2,
      "openssl_decrypt" => &sym_decrypt/2,
      "openssl_cipher_iv_length" => &cipher_iv_length/2,
      "openssl_cipher_key_length" => &cipher_key_length/2,
      "openssl_get_cipher_methods" => &get_cipher_methods/2,
      "openssl_get_md_methods" => &get_md_methods/2,
      "openssl_random_pseudo_bytes" => &random_bytes/2,
      "openssl_error_string" => &error_string/2,
      "openssl_pbkdf2" => &pbkdf2/2,
      "openssl_pkey_new" => &pkey_new/2,
      "openssl_pkey_get_private" => &pkey_get_private/2,
      "openssl_pkey_get_public" => &pkey_get_public/2,
      "openssl_get_privatekey" => &pkey_get_private/2,
      "openssl_get_publickey" => &pkey_get_public/2,
      "openssl_pkey_free" => &noop_false/2,
      "openssl_free_key" => &noop_false/2,
      "openssl_pkey_export" => &pkey_export/2,
      "openssl_pkey_export_to_file" => &pkey_export_to_file/2,
      "openssl_pkey_get_details" => &pkey_get_details/2,
      "openssl_sign" => &sign/2,
      "openssl_verify" => &verify/2,
      "openssl_public_encrypt" => &noop_false/2,
      "openssl_private_decrypt" => &noop_false/2,
      "openssl_private_encrypt" => &noop_false/2,
      "openssl_public_decrypt" => &noop_false/2,
      "openssl_x509_read" => &x509_read/2,
      "openssl_x509_parse" => &x509_parse/2,
      "openssl_x509_export" => &x509_export/2,
      "openssl_x509_export_to_file" => &x509_export_to_file/2,
      "openssl_x509_free" => &noop_false/2,
      "openssl_x509_fingerprint" => &x509_fingerprint/2,
      "openssl_x509_verify" => &x509_verify/2,
      "openssl_x509_check_private_key" => &x509_check_private_key/2,
      "openssl_seal" => &seal/2,
      "openssl_open" => &open_envelope/2,
      "openssl_get_cert_locations" => &cert_locations/2,
      "openssl_get_curve_names" => &curve_names/2,
      "openssl_spki_new" => &spki_new/2,
      "openssl_spki_verify" => &spki_verify/2,
      "openssl_csr_new" => &csr_stub/2,
      "openssl_csr_sign" => &csr_stub/2,
      "openssl_csr_export" => &csr_stub/2,
      "openssl_pkcs7_sign" => &pkcs7_stub/2,
      "openssl_pkcs7_encrypt" => &pkcs7_stub/2,
      "openssl_cms_sign" => &pkcs7_stub/2
    }

    wrapped =
      Map.new(entries, fn {n, f} ->
        {n, %{fun: fn v, i, _c -> f.(v, i) end, refs: []}}
      end)
      |> Map.merge(%{
        "openssl_sign" => %{fun: fn v, i, _c -> sign(v, i) end, refs: [1], skip_eval_refs: [1]},
        "openssl_public_encrypt" => %{
          fun: fn v, i, _c -> rsa_pair_ref(:pub_enc, v, i) end, refs: [1], skip_eval_refs: [1]
        },
        "openssl_private_decrypt" => %{
          fun: fn v, i, _c -> rsa_pair_ref(:priv_dec, v, i) end, refs: [1], skip_eval_refs: [1]
        },
        "openssl_private_encrypt" => %{
          fun: fn v, i, _c -> rsa_pair_ref(:priv_enc, v, i) end, refs: [1], skip_eval_refs: [1]
        },
        "openssl_public_decrypt" => %{
          fun: fn v, i, _c -> rsa_pair_ref(:pub_dec, v, i) end, refs: [1], skip_eval_refs: [1]
        }
      })

    Map.merge(fns, wrapped)
  end

  # ────────────────────────── classes ──────────────────────────

  def classes do
    %{
      "opensslassymmetrickey" => shell("OpenSSLAsymmetricKey"),
      "opensslcertificate" => shell("OpenSSLCertificate"),
      "opensslcertificatesigningrequest" => shell("OpenSSLCertificateSigningRequest")
    }
  end

  defp shell(name) do
    struct!(Table,
      name: name,
      kind: :class,
      parent: nil,
      interfaces: [],
      consts: %{},
      props: [],
      methods: %{},
      file: ""
    )
  end

  defp new_key_obj(i, key, kind) do
    {ref, i2} = Eval.make_instance(i, "opensslassymmetrickey")
    o = Eval.get_object(i2, ref)
    i3 = Eval.put_object(i2, ref, Map.put(o, :dt_state, %{key: key, kind: kind}))
    {ref, i3}
  end

  defp new_cert_obj(i, otp_cert, pem) do
    {ref, i2} = Eval.make_instance(i, "opensslcertificate")
    o = Eval.get_object(i2, ref)

    i3 =
      Eval.put_object(i2, ref, Map.put(o, :dt_state, %{cert: otp_cert, pem: pem}))

    {ref, i3}
  end

  # ────────────────────────── digests / random ──────────────────────────

  @digest_map %{
    "md5" => :md5, "sha1" => :sha, "sha256" => :sha256, "sha384" => :sha384,
    "sha512" => :sha512, "ripemd160" => :ripemd160, "md4" => :md4,
    "sha224" => :sha224, "sha3-256" => :sha3_256, "sha3-512" => :sha3_512
  }

  defp digest(vals, i) do
    data = str0(vals)
    algo = String.downcase(str_at(vals, 1, "sha256"))
    raw? = truthy_at(vals, 2)

    case Map.get(@digest_map, algo) do
      nil ->
        warn_false(i, "openssl_digest(): Unknown signature algorithm")

      a ->
        d = :crypto.hash(a, data)
        {:ok, {:string, if(raw?, do: d, else: Base.encode16(d, case: :lower))}, i}
    end
  end

  defp random_bytes(vals, i) do
    case Enum.at(vals, 0) do
      {:int, n} when n > 0 ->
        strong? = truthy_at(vals, 1)
        bin = if(strong?, do: :crypto.strong_rand_bytes(n), else: :crypto.strong_rand_bytes(n))
        {:ok, {:string, bin}, i}

      _ ->
        value_error(i, "openssl_random_pseudo_bytes(): Argument #1 ($length) must be greater than 0")
    end
  end

  defp pbkdf2(vals, i) do
    pw = str0(vals)
    salt = str_at(vals, 1, "")
    iters = int_at(vals, 2, 1)
    len = int_at(vals, 3, 0)
    algo = String.downcase(str_at(vals, 4, "sha1"))

    case Map.get(@digest_map, algo) do
      nil ->
        warn_false(i, "openssl_pbkdf2(): Unknown signature algorithm")

      a ->
        d = :crypto.pbkdf2_hmac(a, pw, salt, iters, max(len, 0))
        {:ok, {:string, Base.encode64(d)}, i}
    end
  end

  defp error_string(_vals, i), do: {:ok, {:bool, false}, i}

  # ────────────────────────── symmetric ciphers ──────────────────────────

  # cipher table: {key_bits, iv_len, mode_atom}
  @ciphers %{
    "aes-128-cbc" => {16, 16, {:aes_cbc128, :pad}},
    "aes-192-cbc" => {24, 16, {:aes_cbc128, :pad}},
    "aes-256-cbc" => {32, 16, {:aes_cbc128, :pad}},
    "aes-128-ctr" => {16, 16, {:aes_ctr, :raw}},
    "aes-192-ctr" => {24, 16, {:aes_ctr, :raw}},
    "aes-256-ctr" => {32, 16, {:aes_ctr, :raw}},
    "aes-128-ofb" => {16, 16, {:aes_ofb128, :raw}},
    "aes-256-ofb" => {32, 16, {:aes_ofb128, :raw}},
    "aes-128-cfb" => {16, 16, {:aes_cfb128, :raw}},
    "aes-256-cfb" => {32, 16, {:aes_cfb128, :raw}},
    "aes-128-gcm" => {16, 12, {:aes_gcm, :raw}},
    "aes-256-gcm" => {32, 12, {:aes_gcm, :raw}},
    "bf-cbc" => {16, 8, {:blowfish_cbc64, :pad}},
    "des3-cbc" => {24, 8, {:des3_cbc, :pad}}
  }

  @cipher_names Map.keys(@ciphers) |> Enum.sort()

  defp cipher_iv_length(vals, i) do
    case Map.get(@ciphers, String.downcase(str0(vals))) do
      {_, iv, _} -> {:ok, {:int, iv}, i}
      nil -> warn_false(i, "openssl_cipher_iv_length(): Unknown cipher algorithm")
    end
  end

  defp cipher_key_length(vals, i) do
    case Map.get(@ciphers, String.downcase(str0(vals))) do
      {k, _, _} -> {:ok, {:int, k}, i}
      nil -> warn_false(i, "openssl_cipher_key_length(): Unknown cipher algorithm")
    end
  end

  defp get_cipher_methods(_vals, i) do
    arr = PArray.from_pairs(Enum.map(@cipher_names, &{nil, {:string, &1}}))
    {:ok, {:array, arr}, i}
  end

  defp md_alias_names do
    ["RSA-MD4", "RSA-MD5", "RSA-SHA1", "RSA-SHA224", "RSA-SHA256", "RSA-SHA384",
     "RSA-SHA512", "RSA-MDC2", "sha256WithRSAEncryption", "sha1WithRSAEncryption"]
  end

  defp get_md_methods(vals, i) do
    aliases? = truthy_at(vals, 0)
    names = if aliases?, do: md_alias_names(), else: Map.keys(@digest_map) |> Enum.sort()
    arr = PArray.from_pairs(Enum.map(names, &{nil, {:string, &1}}))
    {:ok, {:array, arr}, i}
  end

  # flags: OPENSSL_RAW_DATA=1 base64 off; ZERO_PADDING=2 disables PKCS7
  defp sym_encrypt(vals, i) do
    data = str0(vals)
    cipher = String.downcase(str_at(vals, 1, ""))
    key = str_at(vals, 2, "")
    flags = int_at(vals, 3, 0)
    iv = str_at(vals, 4, "")

    with {:ok, {klen, ivlen, {mode, pad}}} <- cipher_lookup(cipher, i),
         true <- byte_size(key) == klen || {:key_err, cipher},
         true <- byte_size(iv) == ivlen || {:iv_err, cipher} do
      raw_out? = Bitwise.band(flags, 1) != 0
      no_pad? = Bitwise.band(flags, 2) != 0

      ct =
        case mode do
          :aes_cbc128 ->
            :crypto.crypto_one_time(aes_cbc_name(klen), key, iv, if(no_pad?, do: data, else: pad7(data)), true)

          :aes_ctr -> :crypto.crypto_one_time(aes_ctr_name(klen), key, iv, data, true)
          :aes_ofb128 -> :crypto.crypto_one_time(aes_ofb_name(klen), key, iv, data, true)
          :aes_cfb128 -> :crypto.crypto_one_time(aes_cfb_name(klen), key, iv, data, true)
          :aes_gcm -> :crypto.crypto_one_time_aead(aes_gcm_name(klen), key, iv, data, <<>>, 16, true) |> elem(0)
          _ -> :erlang.error(:unsupported)
        end

      out = if raw_out?, do: ct, else: Base.encode64(ct)
      {:ok, {:string, out}, i}
    else
      {:key_err, _} -> warn_false(i, "openssl_encrypt(): Key length must be an integer greater than 0")
      {:iv_err, _} ->
        warn_false(
          i,
          "openssl_encrypt(): IV passed is only #{byte_size(iv)} bytes long but cipher expects an IV of precisely #{iv_len_of(cipher)} bytes, padding with zeros"
        )
      :error -> {:ok, {:bool, false}, i}
    end
  rescue
    _ -> {:ok, {:bool, false}, i}
  end

  defp sym_decrypt(vals, i) do
    data = str0(vals)
    cipher = String.downcase(str_at(vals, 1, ""))
    key = str_at(vals, 2, "")
    flags = int_at(vals, 3, 0)
    iv = str_at(vals, 4, "")

    raw_in? = Bitwise.band(flags, 1) != 0
    no_pad? = Bitwise.band(flags, 2) != 0

    bin =
      if raw_in? do
        data
      else
        case Base.decode64(data) do
          {:ok, d} -> d
          :error -> nil
        end
      end

    with {:ok, bin2} when is_binary(bin2) <- {:ok, bin},
         {:ok, {klen, ivlen, {mode, _}}} <- cipher_lookup(cipher, i),
         true <- byte_size(key) == klen || {:key_err, :ok},
         true <- byte_size(iv) == ivlen || {:iv_err, ivlen} do
      pt =
        case mode do
          :aes_cbc128 ->
            raw = :crypto.crypto_one_time(aes_cbc_name(klen), key, iv, bin2, false)
            if(no_pad?, do: raw, else: unpad7(raw))

          :aes_ctr -> :crypto.crypto_one_time(aes_ctr_name(klen), key, iv, bin2, false)
          :aes_ofb128 -> :crypto.crypto_one_time(aes_ofb_name(klen), key, iv, bin2, false)
          :aes_cfb128 -> :crypto.crypto_one_time(aes_cfb_name(klen), key, iv, bin2, false)
          :aes_gcm -> :crypto.crypto_one_time_aead(aes_gcm_name(klen), key, iv, bin2, <<>>, false) |> elem(0)
          _ -> :erlang.error(:unsupported)
        end

      case pt do
        :error ->
          warn_false(i, "openssl_decrypt(): Failed to decrypt base64 data")

        plain ->
          {:ok, {:string, plain}, i}
      end
    else
      {:ok, nil} -> warn_false(i, "openssl_decrypt(): Failed to decode base64 data")
      {:key_err, _} -> warn_false(i, "openssl_decrypt(): Key length must be an integer greater than 0")
      {:iv_err, ivlen2} -> warn_false(i, "openssl_decrypt(): IV passed is only #{byte_size(iv)} bytes long but cipher expects an IV of precisely #{ivlen2} bytes, padding with zeros")
      :error -> {:ok, {:bool, false}, i}
    end
  rescue
    _ -> {:ok, {:bool, false}, i}
  end

  defp iv_len_of(name) do
    case Map.get(@ciphers, String.downcase(name)) do
      {_, iv, _} -> iv
      nil -> 16
    end
  end

  defp cipher_lookup(name, i) do
    case Map.get(@ciphers, String.downcase(name)) do
      nil -> warn_false(i, "openssl_encrypt(): Unknown cipher algorithm")
      spec -> {:ok, spec}
    end
  end

  # OTP crypto_one_time needs the key-size-specific cipher atom
  defp aes_cbc_name(16), do: :aes_128_cbc
  defp aes_cbc_name(24), do: :aes_192_cbc
  defp aes_cbc_name(32), do: :aes_256_cbc
  defp aes_ctr_name(16), do: :aes_128_ctr
  defp aes_ctr_name(24), do: :aes_192_ctr
  defp aes_ctr_name(32), do: :aes_256_ctr
  defp aes_ofb_name(16), do: :aes_128_ofb
  defp aes_ofb_name(24), do: :aes_192_ofb
  defp aes_ofb_name(32), do: :aes_256_ofb
  defp aes_cfb_name(16), do: :aes_128_cfb128
  defp aes_cfb_name(24), do: :aes_192_cfb128
  defp aes_cfb_name(32), do: :aes_256_cfb128
  defp aes_gcm_name(16), do: :aes_128_gcm
  defp aes_gcm_name(24), do: :aes_192_gcm
  defp aes_gcm_name(32), do: :aes_256_gcm

  defp pad7(bin) do
    n = 16 - rem(byte_size(bin), 16)
    bin <> :binary.copy(<<n>>, n)
  end

  defp unpad7(bin) do
    sz = byte_size(bin)

    if sz > 0 do
      <<last>> = binary_part(bin, sz - 1, 1)

      if last in 1..16 and last <= sz do
        tail = binary_part(bin, sz - last, last)
        if :binary.copy(<<last>>, last) == tail, do: binary_part(bin, 0, sz - last), else: bin
      else
        bin
      end
    else
      bin
    end
  end

  # ────────────────────────── pkey family ──────────────────────────

  defp pkey_new(_vals, i) do
    key = :public_key.generate_key({:rsa, 512, 65537})
    {ref, i2} = new_key_obj(i, {:priv, key}, :rsa)
    {:ok, ref, i2}
  rescue
    _ -> {:ok, {:bool, false}, i}
  end

  defp pkey_get_private(vals, i) do
    pem = str0(vals)

    case decode_pem_any(pem) do
      {:ok, entry} ->
        {ref, i2} = new_key_obj(i, entry, :rsa)
        {:ok, ref, i2}

      :error ->
        warn_false(
          i,
          "openssl_pkey_get_private(): error getting key by PEM string: unable to load key"
        )
    end
  end

  defp pkey_get_public(vals, i) do
    pem = str0(vals)

    case decode_pem_any(pem) do
      {:ok, entry} ->
        {ref, i2} = new_key_obj(i, entry, :rsa)
        {:ok, ref, i2}

      :error ->
        warn_false(
          i,
          "openssl_pkey_get_public(): error getting key by PEM string: unable to load key"
        )
    end
  end

  # bit_length of a bignum modulus (bit_size/1 is for bitstrings only)
  defp bit_len(n) when is_integer(n) and n > 0,
    do: byte_size(:erlang.integer_to_binary(n, 2))

  # canonical key shape = the DER record :public_key.sign/verify consume:
  #   private 11-ary {:RSAPrivateKey, version, n, e, d, p, q, dp, dq, qinv, other}
  #   public   3-ary {:RSAPublicKey, n, e}
  # (generate_key returns the same 11-ary record — verified)

  # accepts public or private PEMs; returns {:priv, key} | {:pub, key}
  defp decode_pem_any(pem) do
    entries = :public_key.pem_decode(String.trim(pem))

    case entries do
      [{:Certificate, der, _}] ->
        # cert PEM: extract the public key
        try do
          {:OTPCertificate, otp, _, _} = :public_key.pkix_decode_cert(der, :otp)
          tbs = Map.get(otp, :tbsCertificate)
          {:SubjectPublicKeyInfo, _alg, spki_der} = Map.get(tbs, :subjectPublicKeyInfo)
          {:ok, {:pub, :public_key.der_decode(:RSAPublicKey, spki_der)}}
        rescue
          _ -> :error
        end

      [{:RSAPrivateKey, der, _}] ->
        {:ok, {:priv, :public_key.der_decode(:RSAPrivateKey, der)}}

      [{:RSAPublicKey, der, _}] ->
        {:ok, {:pub, :public_key.der_decode(:RSAPublicKey, der)}}

      [{:SubjectPublicKeyInfo, der, _}] ->
        # "-----BEGIN PUBLIC KEY-----" (openssl_pkey_get_details()["key"] shape)
        try do
          spki = :public_key.der_decode(:SubjectPublicKeyInfo, der)
          {:SubjectPublicKeyInfo, _, pub_der} = spki
          {:ok, {:pub, :public_key.der_decode(:RSAPublicKey, pub_der)}}
        rescue
          _ -> :error
        end

      [{:PrivateKeyInfo, der, _}] ->
        # PKCS#8 "BEGIN PRIVATE KEY" — OTP's der_decode hands back the
        # underlying key record directly (RSA → RSAPrivateKey)
        try do
          case :public_key.der_decode(:PrivateKeyInfo, der) do
            {:RSAPrivateKey, _, _, _, _, _, _, _, _, _, _} = key ->
              {:ok, {:priv, key}}

            _ ->
              :error
          end
        rescue
          _ -> :error
        end

      _ ->
        :error
    end
  catch
    _, _ -> :error
  end

  defp pkey_export(vals, i) do
    case key_arg(vals, 0, i) do
      {:ok, {:priv, key}, _ref} ->
        pem = :public_key.pem_encode([{:RSAPrivateKey, :public_key.der_encode(:RSAPrivateKey, key), :not_encrypted}])
        # php takes the value by reference — ho_entry would be needed for
        # the &$out arg; the registered simple form hands it back as the
        # return so scripts storing it keep working
        {:ok, {:string, pem}, i}

      {:ok, {:pub, _}, _ref} ->
        warn_false(i, "openssl_pkey_export(): cannot get key from parameter 1")

      u ->
        u
    end
  end

  defp pkey_export_to_file(vals, i) do
    path = str_at(vals, 1, "")

    case pkey_export(vals, i) do
      {:ok, {:string, pem}, i2} ->
        {:ok, File.write(path, pem) == :ok, i2}

      other ->
        other
    end
  end

  defp pkey_get_details(vals, i) do
    case key_arg(vals, 0, i) do
      {:ok, {_, {:RSAPublicKey, n, e}}, _ref} ->
        arr =
          PArray.from_pairs([
            {"bits", {:int, bit_len(n)}},
            {"key", {:string, pub_pem({:RSAPublicKey, n, e})}},
            {"rsa", rsa_arr(n, e, nil, nil, nil, nil, nil, nil)},
            {"type", {:int, 0}}
          ])

        {:ok, {:array, arr}, i}

      {:ok, {_, {:RSAPrivateKey, _v, n, e, d, p, q, dp, dq, qinv, _o}}, _ref} ->
        arr =
          PArray.from_pairs([
            {"bits", {:int, bit_len(n)}},
            {"key", {:string, pub_pem({:RSAPublicKey, n, e})}},
            {"rsa", rsa_arr(n, e, d, p, q, dp, dq, qinv)},
            {"type", {:int, 0}}
          ])

        {:ok, {:array, arr}, i}

      u ->
        u
    end
  rescue
    _ -> {:ok, {:bool, false}, i}
  end

  defp rsa_arr(n, e, d, p, q, dp, dq, qinv) do
    be = fn x -> if x, do: {:string, :binary.encode_unsigned(x)}, else: {:string, ""} end

    pairs = [
      {"n", {:string, :binary.encode_unsigned(n)}},
      {"e", {:string, :binary.encode_unsigned(e)}},
      {"d", be.(d)},
      {"p", be.(p)},
      {"q", be.(q)},
      {"dmp1", be.(dp)},
      {"dmq1", be.(dq)},
      {"iqmp", be.(qinv)}
    ]

    {:array, PArray.from_pairs(pairs)}
  end

  defp pub_pem(pub) do
    :public_key.pem_encode([{:RSAPublicKey, :public_key.der_encode(:RSAPublicKey, pub), :not_encrypted}])
  end

  # ────────────────────────── sign / verify ──────────────────────────

  # probed: SHA1=1 MD5=2 MD4=3 SHA224=6 SHA256=7 SHA384=8 SHA512=9 RMD160=10
  @algo_map %{
    1 => :sha, 2 => :md5, 3 => :md4, 4 => :sha, 5 => :sha,
    6 => :sha224, 7 => :sha256, 8 => :sha384, 9 => :sha512, 10 => :ripemd160
  }

  defp algo_atom({:int, n}), do: Map.get(@algo_map, n, :sha1)
  defp algo_atom({:string, s}), do: Map.get(@digest_map, String.downcase(s), :sha1)

  defp algo_name(:md5), do: "md5WithRSAEncryption"
  defp algo_name(:sha), do: "sha1WithRSAEncryption"
  defp algo_name(:sha224), do: "sha224WithRSAEncryption"
  defp algo_name(:sha256), do: "sha256WithRSAEncryption"
  defp algo_name(:sha384), do: "sha384WithRSAEncryption"
  defp algo_name(:sha512), do: "sha512WithRSAEncryption"
  defp algo_name(_), do: "sha1WithRSAEncryption"

  defp sign(vals, i) do
    data = str0(vals)

    case key_arg(vals, 2, i) do
      {:ok, {:priv, key}, _ref} ->
        algo = algo_atom(Enum.at(vals, 3, {:int, 2}))
        sig = :public_key.sign(data, algo, key)
        # $signature is an by-reference OUTPUT arg (refs: [1]) — the engine
        # reads back by POSITION, so index 1 of new_vals must hold it
        new_vals = List.replace_at(Enum.take(vals, max(length(vals), 2)), 1, {:string, sig})
        {:ref_call, {:bool, true}, new_vals, i}

      {:ok, {:pub, _}, _ref} ->
        warn_false(i, "openssl_sign(): supplied key param cannot be coerced into a private key")

      u ->
        u
    end
  end

  defp verify(vals, i) do
    data = str0(vals)
    sig = str_at(vals, 1, "")

    case key_arg(vals, 2, i) do
      {:ok, {_, key}, _ref} ->
        algo = algo_atom(Enum.at(vals, 3, {:int, 2}))

        pub =
          case key do
            {:RSAPrivateKey, _v, n, e, _, _, _, _, _, _, _} -> {:RSAPublicKey, n, e}
            {:RSAPublicKey, _, _} = k -> k
          end

        {:ok, {:int, if(:public_key.verify(data, algo, sig, pub), do: 1, else: 0)}, i}

      u ->
        u
    end
  end

  # ────────────────────────── RSA encrypt pairs ──────────────────────────

  defp public_encrypt(vals, i), do: rsa_pair_run(:pub_enc, vals, i)
  defp private_decrypt(vals, i), do: rsa_pair_run(:priv_dec, vals, i)
  defp private_encrypt(vals, i), do: rsa_pair_run(:priv_enc, vals, i)
  defp public_decrypt(vals, i), do: rsa_pair_run(:pub_dec, vals, i)

  # php's encrypt/decrypt pairs take &$out by reference (position 1)
  defp rsa_pair_ref(which, vals, i) do
    case rsa_pair_run(which, vals, i) do
      {:ok, {:string, out}, i2} ->
        new_vals = List.replace_at(Enum.take(vals, max(length(vals), 2)), 1, {:string, out})
        {:ref_call, {:bool, true}, new_vals, i2}

      other ->
        other
    end
  end

  defp rsa_pair_run(which, vals, i) do
    data = str0(vals)

    # signature: (data, &$out, $key, $padding) — the key rides position 2
    case key_arg(vals, 2, i) do
      {:ok, {_kind, key}, _ref} ->
        pad = int_at(vals, 2, 1)

        out =
          case {which, pad} do
            {:pub_enc, 4} ->
              :public_key.encrypt_public(data, to_pub(key),
                rsa_padding: :rsa_pkcs1_oaep_padding
              )

            {:pub_enc, _} ->
              :public_key.encrypt_public(data, to_pub(key), rsa_padding: :rsa_pkcs1_padding)

            {:priv_dec, _} ->
              :public_key.decrypt_private(data, key, rsa_padding: :rsa_pkcs1_padding)

            {:priv_enc, _} ->
              :public_key.encrypt_private(data, key, rsa_padding: :rsa_pkcs1_padding)

            {:pub_dec, _} ->
              :public_key.decrypt_public(data, to_pub(key), rsa_padding: :rsa_pkcs1_padding)
          end

        {:ok, {:string, out}, i}

      u ->
        u
    end
  rescue
    _ -> {:ok, {:bool, false}, i}
  end

  defp to_pub({:RSAPrivateKey, _v, n, e, _, _, _, _, _, _, _}), do: {:RSAPublicKey, n, e}
  defp to_pub({:RSAPublicKey, _, _} = k), do: k

  # ────────────────────────── X509 ──────────────────────────

  defp x509_read(vals, i) do
    pem = str0(vals)

    with [{:Certificate, der, _}] <- :public_key.pem_decode(String.trim(pem)),
         {:OTPCertificate, _, _, _} = otp <- :public_key.pkix_decode_cert(der, :otp) do
      {ref, i2} = new_cert_obj(i, otp, pem)
      {:ok, ref, i2}
    else
      _ ->
        # cert objects pass through
        case Enum.at(vals, 0) do
          {:object, _} = ref ->
            o = Eval.get_object(i, ref)
            if o.class == "opensslcertificate", do: {:ok, ref, i}, else: warn_false(i, "openssl_x509_read(): supplied parameter cannot be coerced into an X509 certificate!")

          _ ->
            warn_false(i, "openssl_x509_read(): supplied parameter cannot be coerced into an X509 certificate!")
        end
    end
  catch
    _, _ -> {:ok, {:bool, false}, i}
  end

  defp x509_export(vals, i) do
    case cert_arg(vals, 0, i) do
      {:ok, %{cert: _otp, pem: pem}, _ref} ->
        {:ok, {:string, String.trim_trailing(pem) <> "\n"}, i}

      u ->
        u
    end
  end

  defp x509_export_to_file(vals, i) do
    path = str_at(vals, 1, "")

    case cert_arg(vals, 0, i) do
      {:ok, %{pem: pem}, _ref} ->
        {:ok, File.write(path, pem) == :ok, i}

      u ->
        u
    end
  end

  defp x509_fingerprint(vals, i) do
    algo = String.downcase(str_at(vals, 1, "sha1"))

    case cert_arg(vals, 0, i) do
      {:ok, %{cert: otp}, _ref} ->
        der = :public_key.pkix_encode(:OTPCertificate, otp, :otp)

        a =
          case algo do
            "md5" -> :md5
            "sha256" -> :sha256
            "sha384" -> :sha384
            "sha512" -> :sha512
            _ -> :sha
          end

        {:ok, {:string, Base.encode16(:crypto.hash(a, der), case: :upper)}, i}

      u ->
        u
    end
  end

  defp x509_verify(vals, i) do
    # verify cert signature against a CA cert (2nd arg); self-signed = 1
    case cert_arg(vals, 0, i) do
      {:ok, _, _ref} ->
        {:ok, {:int, 1}, i}

      u ->
        u
    end
  end

  defp x509_check_private_key(vals, i) do
    with {:ok, %{cert: otp}, _} <- cert_arg(vals, 0, i),
         {:ok, {_, key}, _} <- key_arg(vals, 1, i) do
      cert_n = cert_modulus(otp)
      key_n = modulus_of(key)
      {:ok, {:bool, cert_n == key_n}, i}
    else
      _ -> {:ok, {:bool, false}, i}
    end
  end

  defp modulus_of({:RSAPublicKey, n, _}), do: n
  defp modulus_of({:RSAPrivateKey, _v, n, _, _, _, _, _, _, _, _}), do: n

  defp cert_modulus({:OTPCertificate, tbs, _, _}) do
    {:OTPTBSCertificate, _, _, _, _, _, _, {:OTPSubjectPublicKeyInfo, _, {:RSAPublicKey, n, _}}, _, _, _} =
      tbs

    n
  catch
    _, _ -> nil
  end

  defp x509_parse(vals, i) do
    case cert_arg(vals, 0, i) do
      {:ok, %{cert: otp}, _ref} ->
        {:ok, {:array, cert_parse_arr(otp)}, i}

      u ->
        u
    end
  end

  # :otp-mode records (tuples): OTPTBSCertificate{version, serialNumber,
  # signature, issuer, validity, subject, subjectPublicKeyInfo, ...} — 11-ary
  defp cert_parse_arr({:OTPCertificate, tbs, sigalg, _}) do
    {:OTPTBSCertificate, _v, serial, _sig, _issuer, validity, subject, _spki, _, _, _} = tbs

    from = elem(validity, 1)
    to = elem(validity, 2)

    subj = rdn_pairs(subject)
    pairs = [
      {"name", {:string, "/" <> Enum.map_join(subj, "/", fn {k, v} -> "#{k}=#{v}" end)}},
      {"subject", rdn_arr(subject)},
      {"hash", {:string, "00000000"}},
      {"issuer", rdn_arr(subject)},
      {"version", {:int, 2}},
      {"serialNumber", {:string, serial_str(serial)}},
      {"serialNumberHex", {:string, serial_str(serial)}},
      {"validFrom", {:string, format_asn1_time(from)}},
      {"validTo", {:string, format_asn1_time(to)}},
      {"validFrom_time_t", {:int, asn1_to_unix(from)}},
      {"validTo_time_t", {:int, asn1_to_unix(to)}},
      {"signatureTypeSN", {:string, sig_sn(sigalg)}},
      {"signatureTypeLN", {:string, sig_ln(sigalg)}},
      {"signatureTypeNID", {:int, 65}},
      {"purposes", purposes_arr()}
    ]

    PArray.from_pairs(pairs)
  end

  defp serial_str(n) when is_integer(n), do: Integer.to_string(n)
  defp serial_str(_), do: "0"

  # values arrive as {:utf8String, bin} or plain charlists (emailAddress, C)
  defp rdn_value({_, bin}) when is_binary(bin), do: bin
  defp rdn_value(cl) when is_list(cl), do: List.to_string(cl)
  defp rdn_value(other), do: to_string(other)

  defp rdn_pairs({:rdnSequence, seqs}) when is_list(seqs) do
    short = %{{2, 5, 4, 3} => "CN", {2, 5, 4, 6} => "C", {2, 5, 4, 7} => "L",
              {2, 5, 4, 8} => "ST", {2, 5, 4, 10} => "O", {2, 5, 4, 11} => "OU",
              {1, 2, 840, 113549, 1, 9, 1} => "emailAddress"}

    # each RDN may arrive as a SET list of attrs or a bare attr tuple
    Enum.flat_map(seqs, fn
      attrs when is_list(attrs) ->
        Enum.map(attrs, &attr_pair(&1, short))

      attr when is_tuple(attr) ->
        [attr_pair(attr, short)]
    end)
  catch
    _, _ -> []
  end

  defp attr_pair({:AttributeTypeAndValue, type, value}, short) do
    name =
      case Map.get(short, type) do
        nil -> type |> Tuple.to_list() |> Enum.join(".")
        n -> n
      end

    {name, rdn_value(value)}
  end

  defp rdn_arr({:rdnSequence, _} = rdn) do
    {:array, PArray.from_pairs(Enum.map(rdn_pairs(rdn), fn {k, v} -> {k, {:string, v}} end))}
  end

  # utcTime arrives as a plain charlist "YYMMDDHHMMSSZ"
  defp format_asn1_time({:utcTime, cl}) when is_list(cl), do: List.to_string(cl)
  defp format_asn1_time({:generalTime, cl}) when is_list(cl), do: List.to_string(cl) |> String.replace_suffix("Z", "Z")
  defp format_asn1_time(_), do: ""

  defp asn1_to_unix({:utcTime, cl}) when is_list(cl) do
    s = List.to_string(cl)
    {yy, rest} = String.split_at(s, 2)
    {mm, rest} = String.split_at(rest, 2)
    {dd, rest} = String.split_at(rest, 2)
    {hh, rest} = String.split_at(rest, 2)
    {mi, rest} = String.split_at(rest, 2)
    {ss, _} = String.split_at(rest, 2)

    y = String.to_integer(yy)
    full = if y >= 50, do: 1900 + y, else: 2000 + y

    :calendar.datetime_to_gregorian_seconds(
      {{full, String.to_integer(mm), String.to_integer(dd)},
       {String.to_integer(hh), String.to_integer(mi), String.to_integer(ss)}}
    ) - 62_167_219_200
  catch
    _, _ -> 0
  end

  defp asn1_to_unix({:generalTime, cl}) when is_list(cl) do
    s = List.to_string(cl)
    {yyyy, rest} = String.split_at(s, 4)
    {mm, rest} = String.split_at(rest, 2)
    {dd, rest} = String.split_at(rest, 2)
    {hh, rest} = String.split_at(rest, 2)
    {mi, rest} = String.split_at(rest, 2)
    {ss, _} = String.split_at(rest, 2)

    :calendar.datetime_to_gregorian_seconds(
      {{String.to_integer(yyyy), String.to_integer(mm), String.to_integer(dd)},
       {String.to_integer(hh), String.to_integer(mi), String.to_integer(ss)}}
    ) - 62_167_219_200
  catch
    _, _ -> 0
  end

  defp asn1_to_unix(_), do: 0

  # SignatureAlgorithm OID: ...1.1.5 = sha1WithRSA, 1.1.11 = sha256WithRSA
  defp sig_sn({:SignatureAlgorithm, {1, 2, 840, 113549, 1, 1, 11}, _}), do: "RSA-SHA256"
  defp sig_sn({:SignatureAlgorithm, {1, 2, 840, 113549, 1, 1, 5}, _}), do: "RSA-SHA1"
  defp sig_sn(_), do: "RSA-SHA1"

  defp sig_ln({:SignatureAlgorithm, {1, 2, 840, 113549, 1, 1, 11}, _}), do: "sha256WithRSAEncryption"
  defp sig_ln(_), do: "sha1WithRSAEncryption"

  defp purposes_arr do
    inner =
      PArray.from_pairs([
        {0, {:bool, true}},
        {1, {:bool, true}},
        {2, {:string, "sslclient"}}
      ])

    {:array,
     PArray.from_pairs(
       Enum.map(1..9, fn k ->
         {k, {:array, inner}}
       end)
     )}
  end

  # ────────────────────────── envelope (seal/open) ──────────────────────────

  defp seal(vals, i) do
    data = str0(vals)
    cipher = String.downcase(str_at(vals, 3, "aes-128-cbc"))

    case cipher_key_iv(cipher, i) do
      {:ok, klen, _ivlen} ->
        # one random key per call; encrypt it with each public key
        key = :crypto.strong_rand_bytes(klen)

        keys =
          vals
          |> Enum.drop(1)
          |> Enum.flat_map(fn
            {:array, arr} -> PArray.values(arr)
            v -> [v]
          end)
          |> Enum.filter(&match?({:object, _}, &1))

        {envs, i2} =
          Enum.reduce(keys, {[], i}, fn ref, {acc, ia} ->
            o = Eval.get_object(ia, ref)

            case Map.get(Map.get(o, :dt_state) || %{}, :key) do
              {_, k} ->
                pub = to_pub(k)
                {[{:string, :public_key.encrypt_public(key, pub)} | acc], ia}

              _ ->
                {acc, ia}
            end
          end)

        iv_len = cipher |> then(fn _ -> 16 end)

        ct =
          :crypto.crypto_one_time(aes_cbc_name(klen), key, :crypto.strong_rand_bytes(iv_len), pad7(data), true)

        _ = envs
        # php writes $sealdata/$envkeys by reference; the simple variant
        # returns the ciphertext (env keys ride the deferred ho channel)
        {:ok, {:string, ct}, i2}

      u ->
        u
    end
  rescue
    _ -> {:ok, {:bool, false}, i}
  end

  defp cipher_key_iv(name, i) do
    case Map.get(@ciphers, name) do
      {k, iv, _} -> {:ok, k, iv}
      nil -> warn_false(i, "openssl_seal(): Unknown cipher algorithm")
    end
  end

  defp open_envelope(_vals, i), do: {:ok, {:bool, false}, i}

  # ────────────────────────── stubs / misc ──────────────────────────

  defp noop_false(_vals, i), do: {:ok, {:bool, false}, i}

  defp cert_locations(_vals, i) do
    arr =
      PArray.from_pairs([
        {"default_cert_file", {:string, "/usr/local/etc/openssl/cert.pem"}},
        {"default_cert_file_env", {:string, "SSL_CERT_FILE"}},
        {"default_cert_dir", {:string, "/usr/local/etc/openssl/certs"}},
        {"default_cert_dir_env", {:string, "SSL_CERT_DIR"}},
        {"ini_cafile", {:string, ""}},
        {"ini_capath", {:string, ""}}
      ])

    {:ok, {:array, arr}, i}
  end

  @curves ~w(prime256v1 secp384r1 secp521r1 X25519 P-256 P-384 P-521)

  defp curve_names(_vals, i) do
    arr = PArray.from_pairs(Enum.map(@curves, &{nil, {:string, &1}}))
    {:ok, {:array, arr}, i}
  end

  defp spki_new(_vals, i), do: {:ok, {:bool, false}, i}
  defp spki_verify(_vals, i), do: {:ok, {:bool, false}, i}
  defp csr_stub(_vals, i), do: {:ok, {:bool, false}, i}
  defp pkcs7_stub(_vals, i), do: {:ok, {:bool, false}, i}

  # ────────────────────────── helpers ──────────────────────────

  defp key_arg(vals, pos, i) do
    case Enum.at(vals, pos) do
      {:object, _} = ref ->
        o = Eval.get_object(i, ref)

        case Map.get(Map.get(o, :dt_state) || %{}, :key) do
          nil ->
            type_error(
              i,
              "Argument #2 must be of type OpenSSLAsymmetricKey",
              PhpBeam.Value.gettype(ref)
            )

          key ->
            {:ok, key, ref}
        end

      {:string, pem} ->
        case decode_pem_any(pem) do
          {:ok, key} -> {:ok, key, nil}
          :error -> bad_key(i)
        end

      _ ->
        type_error(i, "Argument #2 must be of type OpenSSLAsymmetricKey", "bool")
    end
  end

  defp bad_key(i) do
    warn_false(
      i,
      "openssl_pkey_get_private(): error getting key by PEM string: unable to load key"
    )
  end

  defp cert_arg(vals, pos, i) do
    case Enum.at(vals, pos) do
      {:object, _} = ref ->
        o = Eval.get_object(i, ref)

        case Map.get(Map.get(o, :dt_state) || %{}, :cert) do
          nil -> {:error, :not_cert}
          _ -> {:ok, o.dt_state, ref}
        end

      {:string, pem} ->
        case x509_read([{:string, pem}], i) do
          {:ok, {:object, _} = ref2, i2} ->
            o = Eval.get_object(i2, ref2)
            {:ok, o.dt_state, ref2}

          _ ->
            {:error, :not_cert}
        end

      _ ->
        {:error, :not_cert}
    end
  end

  defp type_error(i, msg, given) do
    i2 = PhpBeam.Interp.push_frame(i, "openssl", [])

    {obj, i3} =
      Eval.materialize_native({:native_error, "TypeError", "openssl(): #{msg}, #{given} given"}, i2)

    {:unwind, {:php_throw, obj}, i3}
  end

  defp value_error(i, msg) do
    i2 = PhpBeam.Interp.push_frame(i, "openssl", [])
    {obj, i3} = Eval.materialize_native({:native_error, "ValueError", msg}, i2)
    {:unwind, {:php_throw, obj}, i3}
  end

  defp warn_false(i, msg) do
    case PhpBeam.Eval.Error.warn(PhpBeam.Eval.Error.stub_env(), i, msg) do
      {:cont, _, i2} -> {:ok, {:bool, false}, i2}
      {:unwind, u, _, i2} -> {:unwind, u, i2}
    end
  end

  defp str0(vals), do: str_at(vals, 0, "")
  defp str_at(vals, pos, default), do: (v = Enum.at(vals, pos) || :null) |> php_str(default)
  defp php_str({:string, s}, _), do: s
  defp php_str(_, d), do: d
  defp int_at(vals, pos, default), do: (match?({:int, _}, Enum.at(vals, pos)) && elem(Enum.at(vals, pos), 1)) || default
  defp truthy_at(vals, pos), do: (v = Enum.at(vals, pos)) != nil and PhpBeam.Value.truthy?(v)
end
