<?php
$a = [3, 1, 2];
sort($a);
echo implode(",", $a), "\n";
rsort($a);
echo implode(",", $a), "\n";
$m = ["b" => 2, "a" => 1];
ksort($m);
echo implode(",", array_keys($m)), "\n";
asort($m);
echo implode(",", array_keys($m)), "\n";
echo array_sum([1, 2, 3]), "|", array_product([2, 3, 4]), "\n";
echo count(["x" => 1, "y" => 2]), "|", count([]), "\n";
$merged = array_merge([1, 2], [3, 4], ["k" => 5]);
echo implode(",", $merged), "|", $merged["k"], "\n";
echo implode(",", array_slice([1,2,3,4,5], 1, 3)), "|", implode(",", array_slice([1,2,3], -2)), "\n";
echo implode(",", array_reverse([1,2,3])), "|", implode(",", array_reverse(["a"=>1,"b"=>2], true)), "\n";
var_dump(in_array(2, [1,2,3]), in_array("2", [1,2], true), array_search(2, [9,8,2]));
echo array_key_exists("k", ["k" => 1]) ? "y" : "n", "\n";
list($x, , $z) = [10, 20, 30];
echo $x, "|", $z, "\n";
["a" => $p, "b" => $q] = ["a" => 1, "b" => 2];
echo $p, "|", $q, "\n";
echo implode(",", array_keys([5 => "a", "x" => "b"])), "\n";
echo implode(",", range(1, 5)), "|", implode(",", range(5, 1)), "|", count(range('a','e')), "\n";
$a2 = [1, 2, 3];
array_push($a2, 4, 5);
echo implode(",", $a2), "|", array_pop($a2), "|", array_shift($a2), "|", implode(",", $a2), "\n";
echo implode(",", array_unique([1, 1, 2, "1", 3])), "\n";
echo implode(",", array_flip(["a" => 1, "b" => 2]) + []), "|";
print_r(array_combine(["x","y"], [1,2]));
echo json_encode(array_chunk([1,2,3,4], 2)), "\n";
echo json_encode(array_diff([1,2,3], [2])), "|", json_encode(array_intersect([1,2,3], [2,4])), "\n";
