<?php
// fixed fixtures generated by php 8.4 (512-bit RSA pair + self-signed cert)
$priv = base64_decode("LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUJWZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQVVBd2dnRThBZ0VBQWtFQXlLcU1vajVRdDhhWGtzV3IKaiswN0NBSlRwblhUZ0JyS0F4d1QyWXBtNDNIemFWZnkwS01BZ3p0Z2xWYnc5cVp1RExNMTN0OXIvUGtnWjFhRwp1bWlXVndJREFRQUJBa0VBeDNtaXEzVyt6N0UrNDh4VUs1THI1NTVJZ1dVSGhvVWE0OVI1ZHZzNkpFVlJuaDYwCjR3TW52bjQ3ZDFTaSsxV21FNDQ3MlZMdmtSWTA1WVF4ZWwzTmdRSWhBUG9zWWw5OTFnNjNmSnBqTGwvMDdQRjEKMDcrMWFabEkxdlFVQlNIR04yTnhBaUVBelZiOHN4MUR3eDliaGM4Q01JZUhwNmJ2Znc5amhoUDVxUEIyZWluSApJa2NDSVFDcU9XTWlXS3c3VFV5Q2ZIUUVwTkpJcGdUVDBDdXZPaW5RNElKeGJiOG9jUUlnZTZralRnc1Z2L0NtCmdaTUZVb3lNV1o3akpMWHp6YzlCejBmaFVmalBBQWtDSVFDYnRvOEFsY3FlYXZiYmFqVE5XcUlLbEVZenFzeFkKK1pnY1I5UGYyZHJ3d0E9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==");
$pub = base64_decode("LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZ3d0RRWUpLb1pJaHZjTkFRRUJCUUFEU3dBd1NBSkJBTWlxaktJK1VMZkdsNUxGcTQvdE93Z0NVNloxMDRBYQp5Z01jRTltS1p1Tng4MmxYOHRDakFJTTdZSlZXOFBhbWJneXpOZDdmYS96NUlHZFdocnBvbGxjQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=");
$sig = base64_decode("Wo6VfTyd6ZpMTJ/+42YjnQ01mYsO6N4pyJbgKSc0pUNmKI3DoPghNklnmE+DK/tFyGwbkIc8f4WLxYJA79sGhA==");
$cert = base64_decode("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNPakNDQWVTZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRVUZBREI3TVJVd0V3WURWUVFEREF4d2FIQmkKWldGdExuUmxjM1F4SFRBYkJna3Foa2lHOXcwQkNRRVdEblJBY0dod1ltVmhiUzUwWlhOME1Rc3dDUVlEVlFRRwpFd0pCVlRFVE1CRUdBMVVFQ0F3S1UyOXRaUzFUZEdGMFpURWhNQjhHQTFVRUNnd1lTVzUwWlhKdVpYUWdWMmxrCloybDBjeUJRZEhrZ1RIUmtNQjRYRFRJMk1Ea3lPVEV6TURnME5Gb1hEVEkzTURreU9URXpNRGcwTkZvd2V6RVYKTUJNR0ExVUVBd3dNY0dod1ltVmhiUzUwWlhOME1SMHdHd1lKS29aSWh2Y05BUWtCRmc1MFFIQm9jR0psWVcwdQpkR1Z6ZERFTE1Ba0dBMVVFQmhNQ1FWVXhFekFSQmdOVkJBZ01DbE52YldVdFUzUmhkR1V4SVRBZkJnTlZCQW9NCkdFbHVkR1Z5Ym1WMElGZHBaR2RwZEhNZ1VIUjVJRXgwWkRCY01BMEdDU3FHU0liM0RRRUJBUVVBQTBzQU1FZ0MKUVFEZ1BVUjRRRWlUb1hHQlY0cHpwVlRpZWUvQXFoZFRXdVhRSFZwN1BaaURTc2Q3WFJ5QUppMkM3UU5CVFg1ZQo5TTRMK0FLOUN1bkZnaWxCRGQxQmtNWFRBZ01CQUFHalV6QlJNQjBHQTFVZERnUVdCQlNzQzZkNkVhdTBoampXClFKbzlaTEF5aGFQZEx6QWZCZ05WSFNNRUdEQVdnQlNzQzZkNkVhdTBoampXUUpvOVpMQXloYVBkTHpBUEJnTlYKSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJCUVVBQTBFQXNUVUhBWTRqWDlLRW1sL3RTOHVxZFhvaApnUENkVVhmSEUyN3JpSlRWbUdxYjdaTFRoZnFDSXVwSWNGNGpRelo3N3VWaXgvUDQwNDZtYytncGF5VUhkZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K");

// digests
var_dump(openssl_digest("abc", "sha256"), openssl_digest("abc", "md5"));

// symmetric ciphers (byte-level)
$e = openssl_encrypt("secret", "aes-128-cbc", "0123456789abcdef", OPENSSL_RAW_DATA, "1111111111111111");
var_dump(bin2hex($e));
var_dump(openssl_decrypt($e, "aes-128-cbc", "0123456789abcdef", OPENSSL_RAW_DATA, "1111111111111111"));
var_dump(bin2hex(openssl_encrypt("secret", "aes-128-cbc", "0123456789abcdef", 0, "1111111111111111")));
$c = openssl_encrypt("data", "aes-256-ctr", str_repeat("k", 32), OPENSSL_RAW_DATA, str_repeat("i", 16));
var_dump(bin2hex($c));
var_dump(openssl_cipher_iv_length("aes-128-cbc"), openssl_cipher_iv_length("nope"));
var_dump(in_array("aes-256-gcm", openssl_get_cipher_methods()));

// RSA sign/verify (fixtures fixed → deterministic)
openssl_sign("hello", $s2, $priv, OPENSSL_ALGO_SHA256);
var_dump($s2 === $sig, openssl_verify("hello", $sig, $pub, OPENSSL_ALGO_SHA256), openssl_verify("tamper", $sig, $pub, OPENSSL_ALGO_SHA256));
openssl_sign("hello", $s3, $priv, OPENSSL_ALGO_SHA1);
var_dump(strlen($s3), openssl_verify("hello", $s3, $pub, OPENSSL_ALGO_SHA1));

// pkey details
$k = openssl_pkey_get_private($priv);
$d = openssl_pkey_get_details($k);
var_dump($d["bits"], bin2hex($d["rsa"]["n"]), bin2hex($d["rsa"]["e"]));

// RSA encrypt pairs
openssl_public_encrypt("abc", $ct, $pub);
var_dump(strlen($ct));
var_dump(openssl_private_decrypt($ct, $pt, $priv), $pt);
openssl_private_encrypt("xy", $ct2, $priv);
var_dump(openssl_public_decrypt($ct2, $pt2, $pub), $pt2);

// X509
$p = openssl_x509_parse($cert);
var_dump($p["subject"]["CN"], $p["subject"]["emailAddress"], $p["validFrom"], $p["name"]);
$co = openssl_x509_read($cert);
var_dump(strlen(openssl_x509_fingerprint($co)), openssl_x509_verify($co, $co), openssl_x509_check_private_key($co, $priv));
